- name: Demonstrate use of tags with NTP configuration
  hosts: all
  gather_facts: no
  vars:
    desired_state: merged

  tasks:

  - name: Set clean state
    tags: clean
    set_fact:
      desired_state: deleted

  - name: Ensure IOSXE NTP Configuration
    when: ansible_network_os == 'cisco.ios.ios'
    cisco.ios.ios_ntp_global:
      config:
        servers:
          - server: "{{ item }}"
            version: 2
      state: "{{desired_state}}"
    loop: "{{ ntp_servers }}"
    tags:
      - deploy

  - name: Ensure NXOS NTP Configuration
    when: ansible_network_os == 'cisco.nxos.nxos'
    cisco.nxos.nxos_ntp_global:
      config:
        servers:
          - server: "{{ item }}"
      state: "{{ desired_state }}"
    loop: "{{ ntp_servers }}"
    tags:
      - deploy
