- name: Demonstrate use of tags with NTP configuration
  hosts: all
  gather_facts: no
  vars:
    ntp_servers:
      - 3.3.3.3
      - 4.4.4.4

  tasks:

  - name: Apply IOSXE NTP Configuration
    when: ansible_network_os == 'cisco.ios.ios'
    cisco.ios.ios_ntp_global:
      config:
        servers:
          - server: "{{ item }}"
            version: 2
      state: merged
    loop: "{{ ntp_servers }}"
    tags:
      - deploy

  - name: Apply NXOS NTP Configuration
    when: ansible_network_os == 'cisco.nxos.nxos'
    cisco.nxos.nxos_ntp_global:
      config:
        servers:
          - server: "{{ item }}"
      state: merged
    loop: "{{ ntp_servers }}"
    tags:
      - deploy

  - name: Remove IOSXE NTP Configuration
    when: ansible_network_os == 'cisco.ios.ios'
    cisco.ios.ios_ntp_global:
      config:
        servers:
          - server: "{{ item }}"
            version: 2
      state: deleted
    loop: "{{ ntp_servers }}"
    tags:
      - clean

  - name: Remove NXOS NTP Configuration
    when: ansible_network_os == 'cisco.nxos.nxos'
    cisco.nxos.nxos_ntp_global:
      config:
        servers:
          - server: "{{ item }}"
      state: deleted
    loop: "{{ ntp_servers }}"
    tags:
      - clean