---
- name: Apply IOSXE logging configuration
  cisco.ios.ios_logging_global:
    config:
      buffered:
        severity: notifications
        size: 12000
      console:
        severity: critical
      facility: local5
      hosts:
        - hostname: 10.10.20.49
        - hostname: 10.10.20.50
      monitor:
        severity: warnings
      snmp_trap:
        - errors
      trap: errors
      userinfo: True
      logging_on: enable
    state: merged
  tags:
    - iosxe
    - logging
    - compliance

- name: Create IOSXE users
  cisco.ios.ios_user:
    aggregate: "{{ local_users }}"
    privilege: 15
    state: present
    update_password: on_create
    purge: no
  tags:
    - iosxe
    - users
    - compliance

- name: Apply clock and service IOSXE configs
  cisco.ios.ios_config:
    lines:
      - clock timezone PST -8 0
      - clock summer-time PDT recurring
      - service timestamps debug datetime msec localtime show-timezone
      - service timestamps log datetime msec localtime show-timezone
  tags:
    - iosxe
    - clock
    - compliance

- name: Apply IOSXE NTP Configuration
  cisco.ios.ios_ntp_global:
    config:
      servers:
        - server: "{{ item }}"
          version: 2
    state: replaced
  loop: "{{ ntp_servers }}"
  tags:
    - iosxe
    - time
    - compliance

- name: Configure IOSXE System Details
  cisco.ios.ios_system:
    domain_name: "{{ domain_name | default('clus2022.com') }}"
    lookup_enabled: no
  tags:
    - iosxe
    - domain
    - compliance