---
# tasks file for bad-rolemance

- name: IOSXE Compliance Deployment
  include_tasks: iosxe_rolemance.yaml
  when: ansible_network_os == "cisco.ios.ios"
  tags:
  - iosxe
  - users
  - compliance

- name: NXOS Compliance Deployment
  include_tasks: nxos_rolemance.yaml
  when: ansible_network_os == "cisco.nxos.nxos"
  tags:
  - nxos
  - users
  - compliance

- name: IOSXE Logging Compliance Deployment
  include_tasks: iosxe_rolemance.yaml
  when: ansible_network_os == "cisco.ios.ios"
  tags:
  - iosxe
  - logging
  - compliance

- name: NXOS Logging Compliance Deployment
  include_tasks: nxos_rolemance.yaml
  when: ansible_network_os == "cisco.nxos.nxos"
  tags:
  - nxos
  - logging
  - compliance

- name: IOSXE Time Compliance Deployment
  include_tasks: iosxe_rolemance.yaml
  when: ansible_network_os == "cisco.ios.ios"
  tags:
  - iosxe
  - time
  - compliance

- name: NXOS Time Compliance Deployment
  include_tasks: nxos_rolemance.yaml
  when: ansible_network_os == "cisco.nxos.nxos"
  tags:
  - nxos
  - time
  - compliance

- name: IOSXE Domain Compliance Deployment
  include_tasks: iosxe_rolemance.yaml
  when: ansible_network_os == "cisco.ios.ios"
  tags:
  - iosxe
  - domain
  - compliance

- name: NXOS Domain Compliance Deployment
  include_tasks: nxos_rolemance.yaml
  when: ansible_network_os == "cisco.nxos.nxos"
  tags:
  - nxos
  - domain
  - compliance